import { Prisma } from "@prisma/client";
import { CoachIntake, aiProvider } from "./ai";
import { buildCompleteUserFitnessContext } from "./coach-context";
import { generateAdvancedNutritionGuidance, generateAdvancedWorkoutWeek } from "./fitness-generation";
import { prisma } from "./prisma";
import { intakeZod } from "./schemas/coach";

export async function saveWorkoutPlanFromSuggestion(userId: string, suggestion: {
  title: string;
  split?: string;
  summary?: string;
  days: {
    name: string;
    dayOfWeek?: string;
    focus?: string;
    rationale?: string;
    coachTip?: string;
    targetDurationMins?: number;
    exercises: {
      name: string;
      muscleGroup: string;
      sets: number;
      reps: number;
      restSeconds?: number;
      notes?: string;
    }[];
  }[];
}) {
  const planCreateInput: Prisma.WorkoutPlanCreateInput = {
    title: suggestion.title,
    split: suggestion.split ?? "",
    summary: suggestion.summary ?? "Generated by FitPilot coach",
    user: { connect: { id: userId } },
    days: {
      create: suggestion.days.map<Prisma.WorkoutDayCreateWithoutWorkoutPlanInput>((day, dayIndex) => ({
        name: day.name,
        dayOfWeek: day.dayOfWeek ?? null,
        focus: day.focus ?? "",
        rationale: day.rationale ?? null,
        coachTip: day.coachTip ?? null,
        targetDurationMins: day.targetDurationMins ?? null,
        order: dayIndex,
        exercises: {
          create: day.exercises.map<Prisma.ExerciseCreateWithoutWorkoutDayInput>((exercise, exerciseIndex) => ({
            name: exercise.name,
            muscleGroup: exercise.muscleGroup,
            sets: exercise.sets,
            reps: exercise.reps,
            restSeconds: exercise.restSeconds ?? 90,
            notes: exercise.notes ?? null,
            order: exerciseIndex,
          })),
        },
      })),
    },
  };

  await prisma.workoutPlan.deleteMany({ where: { userId } });

  return prisma.workoutPlan.create({
    data: planCreateInput,
    include: {
      days: {
        orderBy: { order: "asc" },
        include: { exercises: { orderBy: { order: "asc" } } },
      },
    },
  });
}

export function buildContextFromIntake(intake: CoachIntake) {
  const parts: string[] = [];

  if (intake.goal) parts.push(`Goal: ${intake.goal}`);
  if (intake.weight) parts.push(`Weight: ${intake.weight}kg`);
  if (intake.height) parts.push(`Height: ${intake.height}cm`);
  if (intake.age) parts.push(`Age: ${intake.age}`);
  if (intake.experience) parts.push(`Experience: ${intake.experience}`);
  if (intake.injuries) parts.push(`Injuries or limitations: ${intake.injuries}`);
  if (intake.daysPerWeek) parts.push(`Training days per week: ${intake.daysPerWeek}`);
  if (intake.sessionDuration) parts.push(`Session duration: ${intake.sessionDuration} minutes`);
  if (intake.location) parts.push(`Training location: ${intake.location}`);
  if (intake.equipment) parts.push(`Equipment access: ${intake.equipment}`);
  if (intake.style) parts.push(`Preferred training style: ${intake.style}`);
  if (intake.cardio) parts.push(`Cardio preference: ${intake.cardio}`);
  if (intake.dislikes) parts.push(`Exercise dislikes: ${intake.dislikes}`);
  if (intake.energySchedule) parts.push(`Energy or schedule notes: ${intake.energySchedule}`);
  if (intake.summary) parts.push(`Coach summary: ${intake.summary}`);

  parts.push(
    "Safety: avoid medical claims, prefer joint-friendly variations when relevant, and keep recommendations practical."
  );

  return parts.join(" | ");
}

export async function generatePlanFromIntake(userId: string, intake: CoachIntake) {
  const context = await buildCompleteUserFitnessContext(userId);
  const generated = await generateAdvancedWorkoutWeek({
    ...context,
    latestIntake: {
      ...context.latestIntake,
      goal: intake.goal ?? context.latestIntake?.goal,
      experience: intake.experience ?? context.latestIntake?.experience,
      injuries: intake.injuries ?? context.latestIntake?.injuries,
      daysPerWeek: intake.daysPerWeek ?? context.latestIntake?.daysPerWeek,
      sessionDuration: intake.sessionDuration ?? context.latestIntake?.sessionDuration,
      location: intake.location ?? context.latestIntake?.location,
      equipment: intake.equipment ?? context.latestIntake?.equipment,
      summary: intake.summary ?? context.latestIntake?.summary,
      safetyNote: intake.safetyNote ?? context.latestIntake?.safetyNote,
    },
    promptContext: `${context.promptContext}\nLatest intake capture: ${buildContextFromIntake(intake)}`,
  });

  const plan = await saveWorkoutPlanFromSuggestion(userId, generated.suggestion);
  return { plan, suggestion: generated.suggestion, source: generated.source, error: generated.error };
}

export async function generateNutritionFromIntake(userId: string, intake: CoachIntake) {
  const context = await buildCompleteUserFitnessContext(userId);
  const generated = await generateAdvancedNutritionGuidance({
    ...context,
    latestIntake: {
      ...context.latestIntake,
      goal: intake.goal ?? context.latestIntake?.goal,
      experience: intake.experience ?? context.latestIntake?.experience,
      injuries: intake.injuries ?? context.latestIntake?.injuries,
      daysPerWeek: intake.daysPerWeek ?? context.latestIntake?.daysPerWeek,
      sessionDuration: intake.sessionDuration ?? context.latestIntake?.sessionDuration,
      location: intake.location ?? context.latestIntake?.location,
      equipment: intake.equipment ?? context.latestIntake?.equipment,
      summary: intake.summary ?? context.latestIntake?.summary,
      safetyNote: intake.safetyNote ?? context.latestIntake?.safetyNote,
    },
    promptContext: `${context.promptContext}\nLatest intake capture: ${buildContextFromIntake(intake)}`,
  });

  await prisma.nutritionPlan.deleteMany({ where: { userId } });

  const nutritionCreateInput: Prisma.NutritionPlanCreateInput = {
    user: { connect: { id: userId } },
    calories: generated.suggestion.calories,
    protein: generated.suggestion.protein,
    carbs: generated.suggestion.carbs,
    fat: generated.suggestion.fat,
    guidance: generated.suggestion.guidance ?? null,
    sampleMeals: JSON.stringify(generated.suggestion.meals),
  };

  const plan = await prisma.nutritionPlan.create({
    data: nutritionCreateInput,
  });

  return { plan, suggestion: generated.suggestion, source: generated.source, error: generated.error };
}

export async function extractCoachIntakeFromMessages(_sessionId: string, transcriptText: string) {
  void _sessionId;
  const ai = await aiProvider.analyzeIntake(transcriptText);

  if (ai.ok) {
    const parsed = intakeZod.safeParse(ai.data);
    if (parsed.success) return parsed.data;
  }

  const safety = "Consult a medical professional for injuries or pain, and use pain-free exercise variations.";

  return {
    summary: "Coach intake captured from the conversation with a conservative fallback summary.",
    safetyNote: safety,
  };
}

export function buildRationale(intake: CoachIntake) {
  const reasons: string[] = [];

  if (intake.goal) reasons.push(`The plan is anchored to your stated goal of ${intake.goal}.`);
  if (intake.daysPerWeek) reasons.push(`Weekly frequency is matched to ${intake.daysPerWeek} training days.`);
  if (intake.sessionDuration) reasons.push(`Session density was kept realistic for ${intake.sessionDuration}-minute workouts.`);
  if (intake.injuries) reasons.push(`Exercise choices avoid obvious aggravators related to ${intake.injuries}.`);
  if (intake.equipment) reasons.push(`Movements stay inside your available equipment: ${intake.equipment}.`);
  if (intake.location) reasons.push(`The structure fits a ${intake.location.toLowerCase()} setup instead of assuming a generic full gym.`);
  if (intake.cardio) reasons.push(`Conditioning work reflects your cardio preference: ${intake.cardio}.`);

  return reasons.length
    ? reasons.join(" ")
    : "The plan balances schedule, recovery, and realistic exercise selection instead of using a generic template.";
}
